name: Deploy laptop.lab Caddy Config

on:
  push:
    branches: [main]
    paths:
      - "caddy/laptop.lab.Caddyfile"
  workflow_dispatch:

jobs:
  deploy-caddy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.INFRA_PRIVATE_KEY }}" > ~/.ssh/infra
          chmod 600 ~/.ssh/infra
          ssh-keyscan -H mtib.dev >> ~/.ssh/known_hosts

      - name: Deploy caddy config to laptop.lab.vpn.mm via mtib.dev
        run: |
          # First copy to mtib.dev as staging
          scp -i ~/.ssh/infra -o StrictHostKeyChecking=no \
            caddy/laptop.lab.Caddyfile \
            root@mtib.dev:/tmp/laptop.lab.Caddyfile

          # Then copy from mtib.dev to laptop.lab.vpn.mm
          ssh -i ~/.ssh/infra -o StrictHostKeyChecking=no root@mtib.dev \
            "scp -i ~/.ssh/infra -o StrictHostKeyChecking=no \
             /tmp/laptop.lab.Caddyfile \
             root@laptop.lab.vpn.mm:/etc/caddy/Caddyfile"

          # Clean up staging file
          ssh -i ~/.ssh/infra -o StrictHostKeyChecking=no root@mtib.dev \
            "rm /tmp/laptop.lab.Caddyfile"
          
          # Reload Caddy on laptop.lab.vpn.mm
          ssh -i ~/.ssh/infra -o StrictHostKeyChecking=no root@mtib.dev \
            "ssh -i ~/.ssh/infra -o StrictHostKeyChecking=no root@laptop.lab.vpn.mm \
             'systemctl reload caddy'"
